apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-app
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: sso-app
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "no-oauth2"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"