apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: production

images:
- name: ghcr.io/linhne14/spring-mvc-crud
  newTag: latest