# Horizontal Pod Autoscaler for SSO Application
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sso-app-hpa
  namespace: sso-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sso-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30
      selectPolicy: Max
---
# Pod Disruption Budget
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sso-app-pdb
  namespace: sso-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sso-app
---
# Resource Quota for namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sso-quota
  namespace: sso-app
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
    pods: "20"